### ISSUE TITLE
stub vs pages

### ISSUE THREAD

**Issue by max-mapper** [derhuerst/build-wikipedia-feed#1]
Hi! Awesome module :)

I have a question about the readme. On https://meta.wikimedia.org/wiki/Data_dumps/Dump_format is says the 'stub' files "contain header information only for pages and revisions, omitting the actual page content". If I wanted to get the full pages, can I just use "pages-meta-current.xml.bz2" from "Recombine all pages, current versions only."?

**Comment by derhuerst** [comment]
Currently, `build-wikipedia-feed` only uses the metadata from the dumps, so you need to feed a `${wiki}-${date}-stub-meta-current.xml.gz` or a `${wiki}-${date}-pages-meta-history${i}.xml-p${from}p${to}.bz2` file into it. It fetches the appropriate version of each article from [the mobile Wikipedia](https://en.wikipedia.org/wiki/Barack_Obama?useformat=mobile).

The reason is that I didn't bother parsing Wikitext, as [there is no real standard](https://www.mediawiki.org/wiki/Wikitext). [Parsoid, the official Wikimedia Wikitext parser](https://www.mediawiki.org/wiki/Parsoid) is too large and hard to work with (I got it working after ~1h work but decided that this can't be the solution) and [a Regex-based npm package](https://github.com/spencermountain/wtf_wikipedia) is too limited. Edit: see [the `render-wikipedia-article` readme](https://github.com/derhuerst/render-wikipedia-article/tree/02d2d4b719df59dd5c5266b3bd6b11d02a3f1c45#render-wikipedia-article).

**Comment by max-mapper** [comment]
Ah wow, what a mess. Very clever using the mobile site. I guess that will grab will the inline images as well?

**Comment by derhuerst** [comment]
> I guess that will grab will the inline images as well?

No. Currently it just downloads the HTML. But since the image links all contain a host, it works fine. I guess it would be reasonably easy to grab the images as well, with little edge cases in how they're embedded.
